"""replace status str with is_online bool

Revision ID: 239c4bf28d85
Revises: e9e5cbe6ce01
Create Date: 2026-06-24 12:41:11.078599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239c4bf28d85'
down_revision: Union[str, Sequence[str], None] = 'e9e5cbe6ce01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.drop_column('printers', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('printers', 'is_online')
    # ### end Alembic commands ###
