"""Add many to many

Revision ID: c7702c1bbc77
Revises: 56a2d6ef0c91
Create Date: 2026-06-29 13:57:28.874490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7702c1bbc77'
down_revision: Union[str, Sequence[str], None] = '56a2d6ef0c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer_cartridge',
    sa.Column('printer_id', sa.UUID(), nullable=False),
    sa.Column('cartridge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('printer_id', 'cartridge_id')
    )
    op.drop_index(op.f('ix_cartridges_printer_model'), table_name='cartridges')
    op.drop_column('cartridges', 'printer_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridges', sa.Column('printer_model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_cartridges_printer_model'), 'cartridges', ['printer_model'], unique=False)
    op.drop_table('printer_cartridge')
    # ### end Alembic commands ###
