"""Init

Revision ID: e709513af1ed
Revises: 
Create Date: 2026-06-30 13:26:28.585381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e709513af1ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartridges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shop_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridges_name'), 'cartridges', ['name'], unique=False)
    op.create_table('printers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('toner_black', sa.Integer(), nullable=True),
    sa.Column('toner_cyan', sa.Integer(), nullable=True),
    sa.Column('toner_magenta', sa.Integer(), nullable=True),
    sa.Column('toner_yellow', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('printer_cartridge',
    sa.Column('printer_id', sa.UUID(), nullable=False),
    sa.Column('cartridge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('printer_id', 'cartridge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer_cartridge')
    op.drop_table('printers')
    op.drop_index(op.f('ix_cartridges_name'), table_name='cartridges')
    op.drop_table('cartridges')
    # ### end Alembic commands ###
